# Generated by Django 3.0.8 on 2020-09-04 23:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userEmail', models.EmailField(default='a@gmail.com', max_length=255, unique=True, verbose_name='User Email')),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('confirmedEmail', models.BooleanField(default=False)),
                ('userNickName', models.CharField(default='NickName', max_length=64, verbose_name='User Nickname')),
                ('userGender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('ETC', 'etc')], default='ETC', max_length=10)),
                ('dateRegistered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cloth_Specific',
            fields=[
                ('clothID', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='closetID')),
                ('color', models.CharField(default='NONE', max_length=64, verbose_name='cloth color')),
                ('season', multiselectfield.db.fields.MultiSelectField(choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall'), ('WINTER', 'Winter'), ('ETC', 'etc')], default='ETC', max_length=29)),
                ('category', models.CharField(choices=[('TOP', 'Top'), ('BOTTOM', 'Bottom'), ('DRESS', 'Dress'), ('OUTER', 'Outer'), ('ETC', 'etc')], default='ETC', max_length=10)),
                ('photo', models.ImageField(default='button/media/default.jpg', upload_to='')),
                ('dateBought', models.DateField(default=datetime.date(2020, 9, 4), verbose_name='date Bought')),
                ('dateLastWorn', models.DateField(default=datetime.date(2020, 9, 4), verbose_name='date Last Worn')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
