# Generated by Django 3.0.8 on 2020-09-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userEmail', models.EmailField(default='a@gmail.com', max_length=255, unique=True, verbose_name='User Email')),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('confirmedEmail', models.BooleanField(default=False)),
                ('userNickName', models.CharField(default='NickName', max_length=64, verbose_name='User Nickname')),
                ('userGender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('ETC', 'etc')], default='ETC', max_length=10)),
                ('dateRegistered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
