# Generated by Django 3.0.8 on 2020-09-08 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth_specific',
            name='dateBought',
            field=models.DateField(default=datetime.date(2020, 9, 8), verbose_name='date Bought'),
        ),
        migrations.AlterField(
            model_name='cloth_specific',
            name='dateLastWorn',
            field=models.DateField(default=datetime.date(2020, 9, 8), verbose_name='date Last Worn'),
        ),
    ]
