# Generated by Django 3.0.8 on 2020-09-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('button_api', '0002_cloth_specific'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth_specific',
            old_name='closetID',
            new_name='id',
        ),
    ]
